IE table fix
PredixDev/px-file-upload pull request #16
Opened 2017-08-10 22:45 UTC by talimarcus

- implement fileTable using `<div>` instead of `<table>` so that it works with dom-repeat in IE11
- remove unnecessary dependencies and sass imports
-

2017-08-11 21:15 UTC, nonmetalhail requested changes
No test changes?

2017-08-11 21:15 UTC, nonmetalhail commented on sass/px-file-upload.scss
> +$inuit-enable-margins--large : true;
Do you need all these padding and margins? I dont see many being used

2017-08-11 21:15 UTC, nonmetalhail commented on px-file-upload.html
> +            <div class="file-upload-th"></div>
Why this last one that is empty?

2017-08-11 21:37 UTC, talimarcus commented on px-file-upload.html
> +            <div class="file-upload-th"></div>
that's to extend the header row to include the column with the X icon at the end of each row. looks like this without it:

![screen shot 2017-08-11 at 2 28 47 pm](https://user-images.githubusercontent.com/9092541/29232619-6b69f3c4-7ea1-11e7-9832-eb6c146fc6af.png)

2017-08-11 21:39 UTC, talimarcus commented on sass/px-file-upload.scss
> +$inuit-enable-margins--large : true;
all of these are being used -- some in the sass and some in the html (`u-p-`, `u-pb+`, etc)

2017-08-11 22:02 UTC, talimarcus commented
@nonmetalhail tests all still passing

2017-08-11 22:07 UTC, nonmetalhail approved these changes

2017-08-11 22:08 UTC, merged

2017-08-13 19:35 UTC, kngauriet reviewed
It works perfect. Thank you very much.